spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2DB;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=true
    username: admin
    password: password
  h2:
    console:
      enabled: true

data.jdbc.json-support: byte_array
