name: Build car department

on:
  push:
    branches: [ master, spring-app ]
    paths:
      - car-department/**
      - .github/workflows/build.car-department.yml
  pull_request:
    branches: [ master ]
    paths:
      - car-department/**
      - .github/workflows/build.car-department.yml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test --tests "*"
