name: Build car department

on:
  push:
    branches:
      - main
      - spring-app
    paths:
      - car-department
  pull_request:
    branches:
      - main
    paths:
    - car-department

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build
