name: Build car department

on:
  push:
    branches:
      - main
      - spring-app
    paths:
      - car-department
  pull_request:
    branches:
      - main
    paths:
      - car-department

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Grant execution permission for gradlew
        run: chmod +x ./car-department/gradlew
      - name: Build with Gradle
        run: ./car-department/gradlew build
      - name: Test service
        run: ./car-department/gradlew -p car-department test
