name: Build car department

on:
  push:
    branches:
      - main
      - spring-app
    paths:
      - car-department
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Test service
        run: ./gradlew -p car-department test
